
# default
server:
    port: 8888

## discovery name: config-server
spring:
    application:
        name: marketplace-config-server
###############################################################################
# spring cloud config server
## path to configuration sources
## use git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/nkolytschew/inspectit-marketplace-configs